#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. See accompanying LICENSE file.
#
baseurl = "https://kyuubi.apache.org"
title = "Apache Kyuubi"
copyright = "Copyright © 2021-{year}"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
uglyurls = true
googleAnalytics = "UA-7453027-1"
contentDir = "src"
publishDir = "content"
defaultContentLanguage = 'en'

[[menu.main]]
  name = "Download"
  url = "releases.html"
  weight = 1

[[menu.main]]
  name = "Docs"
  identifier = "docs"
  weight = 2

[[menu.main]]
  name = "master (dev-only)"
  parent = "docs"
  url = "https://kyuubi.readthedocs.io/en/master/"
  weight = 1


[[menu.main]]
  name = "Community"
  identifier = "community"
  weight = 3

[[menu.main]]
  name = "Code of Conduct"
  url = "https://www.apache.org/foundation/policies/conduct"
  parent = "community"
  weight = 1

[[menu.main]]
  name = "Development"
  identifier = "development"
  weight = 4

[[menu.main]]
  name = "Users"
  identifier = "powered"
  url = "powered_by.html"
  weight = 5

[[menu.main]]
  name = "Github"
  identifier = "github"
  weight = 6

[[menu.main]]
  name = "kyuubi"
  parent = "github"
  url = "https://github.com/apache/kyuubi"
  weight = 1

[[menu.main]]
  name = "kyuubi-client"
  parent = "github"
  url = "https://github.com/apache/kyuubi-client"
  weight = 2

[[menu.main]]
  name = "kyuubi-docker"
  parent = "github"
  url = "https://github.com/apache/kyuubi-docker"
  weight = 3

[[menu.main]]
  name = "kyuubi-website"
  parent = "github"
  url = "https://github.com/apache/kyuubi-website"
  weight = 4

[[menu.main]]
  name = "ASF"
  identifier = "asf"
  weight = 7

[[menu.main]]
  name = "Foundation"
  url = "https://www.apache.org/"
  parent = "asf"

[[menu.main]]
  name = "License"
  url = "https://www.apache.org/licenses/"
  parent = "asf"

[[menu.main]]
  name = "Events"
  url = "https://www.apache.org/events/current-event"
  parent = "asf"

[[menu.main]]
  name = "Security"
  url = "https://www.apache.org/security/"
  parent = "asf"

[[menu.main]]
  name = "Sponsorship"
  url = "https://www.apache.org/foundation/sponsorship.html"
  parent = "asf"

[[menu.main]]
  name = "Thanks"
  url = "https://www.apache.org/foundation/thanks.html"
  parent = "asf"

[[menu.main]]
  name = "Privacy Policy"
  url = "https://privacy.apache.org/policies/privacy-policy-public.html"
  parent = "asf"

[[menu.main]]
  name = "Language"
  identifier = "language"
  weight = 7

[[menu.main]]
  parent = "language"

# chinese menu
[[languages.zh.menu.main]]
  name = "下载"
  url = "zh/releases.html"
  weight = 1

[[languages.zh.menu.main]]
  name = "文档"
  identifier = "docs"
  weight = 2

[[languages.zh.menu.main]]
  name = "master (dev-only)"
  parent = "docs"
  url = "https://kyuubi.readthedocs.io/en/master/"
  weight = 1

[[languages.zh.menu.main]]
  name = "社区"
  identifier = "community"
  weight = 3

[[languages.zh.menu.main]]
  name = "行为守则"
  url = "https://www.apache.org/foundation/policies/conduct"
  parent = "community"
  weight = 1

[[languages.zh.menu.main]]
  name = "发展"
  identifier = "development"
  weight = 4

[[languages.zh.menu.main]]
  name = "用户"
  identifier = "powered"
  url = "zh/powered_by.html"
  weight = 5

[[languages.zh.menu.main]]
  name = "Github"
  identifier = "github"
  weight = 6

[[languages.zh.menu.main]]
  name = "kyuubi"
  parent = "github"
  url = "https://github.com/apache/kyuubi"
  weight = 1

[[languages.zh.menu.main]]
  name = "kyuubi-client"
  parent = "github"
  url = "https://github.com/apache/kyuubi-client"
  weight = 2

[[languages.zh.menu.main]]
  name = "kyuubi-docker"
  parent = "github"
  url = "https://github.com/apache/kyuubi-docker"
  weight = 3

[[languages.zh.menu.main]]
  name = "kyuubi-website"
  parent = "github"
  url = "https://github.com/apache/kyuubi-website"
  weight = 4

[[languages.zh.menu.main]]
  name = "ASF"
  identifier = "asf"
  weight = 7

[[languages.zh.menu.main]]
  name = "基金会"
  url = "https://www.apache.org/"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "License"
  url = "https://www.apache.org/licenses/"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "活动"
  url = "https://www.apache.org/events/current-event"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "安全"
  url = "https://www.apache.org/security/"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "赞助"
  url = "https://www.apache.org/foundation/sponsorship.html"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "感谢"
  url = "https://www.apache.org/foundation/thanks.html"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "隐私条款"
  url = "https://privacy.apache.org/policies/privacy-policy-public.html"
  parent = "asf"

[[languages.zh.menu.main]]
  name = "Language"
  identifier = "language"
  weight = 7

[[languages.zh.menu.main]]
  parent = "language"

# Configure the English version of the website.
[languages.en]
  languageCode = "en-us"
  contentDir = 'src/en'

[languages.zh]
  languageCode = "zh-cn"
  contentDir = 'src/zh'

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.asciidocExt]
    backend = 'html5'
    extensions = []
    failureLevel = 'fatal'
    noHeaderOrFooter = true
    preserveTOC = false
    safeMode = 'unsafe'
    sectionNumbers = false
    trace = false
    verbose = false
    workingFolderCurrent = false
    [markup.asciidocExt.attributes]
  [markup.blackFriday]
    angledQuotes = false
    footnoteAnchorPrefix = ''
    footnoteReturnLinkContents = ''
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    nofollowLinks = false
    noreferrerLinks = false
    plainIDAnchors = true
    skipHTML = false
    smartDashes = true
    smartypants = true
    smartypantsQuotesNBSP = false
    taskLists = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
      goldmark-emoji = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2


# Configure minify.
[minify]
  [minify.tdewolff.html]
    keepQuotes = true

[params]
  latestRelease = '1.10.0'
  releases = [ 'v1.10.0','v1.9.3', 'v1.8.3', 'v1.7.4', 'v1.6.1-incubating', 'v1.5.2-incubating', 'v1.4.1-incubating', 'v1.3.1-incubating' ]
  downloadLink = 'https://www.apache.org/dyn/closer.lua/kyuubi/'
  downloadLinkIncubator = 'https://www.apache.org/dyn/closer.lua/incubator/kyuubi/'
